import { mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { defineConfig, loadEnv, type Plugin } from 'vite';

import { VitePWA } from 'vite-plugin-pwa';
import appConfig from '../app-config/index.js';

const frontendDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(frontendDir, '..');
const appConfigAlias = resolve(repoRoot, 'app-config/index.mjs');
const buzzerSoundsDir = resolve(frontendDir, 'public', 'buzzer-sounds');

// Vite plugin to generate buzzer sounds manifest
function buzzerSoundsManifestPlugin(): Plugin {
  const generateManifest = () => {
    const utilsDir = resolve(frontendDir, 'src', 'utils');
    const manifestPath = resolve(utilsDir, 'buzzerSoundsManifest.ts');

    try {
      const files = readdirSync(buzzerSoundsDir);
      const mp3Files = files
        .filter((file) => file.toLowerCase().endsWith('.mp3'))
        .map((file) => `/buzzer-sounds/${file}`);

      // Format array with single quotes to match project style
      const formattedFiles = mp3Files.map((file) => `  '${file}'`).join(',\n');
      const manifestContent = `// This file is auto-generated by the buzzer-sounds-manifest Vite plugin
// Do not edit manually. Add/remove MP3 files in public/buzzer-sounds/ instead.

export const BUZZER_SOUNDS: string[] = [
${formattedFiles},
];
`;

      // Ensure utils directory exists
      try {
        mkdirSync(utilsDir, { recursive: true });
      } catch {
        // Directory already exists
      }

      writeFileSync(manifestPath, manifestContent, 'utf-8');
    } catch {
      // Directory might not exist or be empty, create empty manifest
      try {
        mkdirSync(utilsDir, { recursive: true });
      } catch {
        // Directory already exists
      }
      writeFileSync(
        manifestPath,
        `// This file is auto-generated by the buzzer-sounds-manifest Vite plugin
// No MP3 files found in public/buzzer-sounds/

export const BUZZER_SOUNDS: string[] = [];
`,
        'utf-8'
      );
    }
  };

  return {
    name: 'buzzer-sounds-manifest',
    buildStart() {
      generateManifest();
    },
    configureServer(server) {
      // Watch the buzzer-sounds directory for changes
      server.watcher.add(buzzerSoundsDir);
      server.watcher.on('add', (path) => {
        const normalizedPath = resolve(path);
        if (
          normalizedPath.startsWith(buzzerSoundsDir) &&
          normalizedPath.toLowerCase().endsWith('.mp3')
        ) {
          generateManifest();
        }
      });
      server.watcher.on('unlink', (path) => {
        const normalizedPath = resolve(path);
        if (
          normalizedPath.startsWith(buzzerSoundsDir) &&
          normalizedPath.toLowerCase().endsWith('.mp3')
        ) {
          generateManifest();
        }
      });
    },
  };
}

export default defineConfig(({ mode }) => {
  // Load env file based on `mode` in the current working directory.
  // Set the third parameter to '' to load all env regardless of the `VITE_` prefix.
  // This also checks process.env, so it works in CI/CD where env vars are set directly.
  const env = loadEnv(mode, repoRoot, '');

  return {
    envDir: repoRoot,
    define: {
      // Make SPOTIFY_CLIENT_ID available in frontend code (Vite only exposes VITE_* vars by default)
      // This replaces import.meta.env.SPOTIFY_CLIENT_ID at build time with the actual value
      'import.meta.env.SPOTIFY_CLIENT_ID': JSON.stringify(
        env.SPOTIFY_CLIENT_ID || process.env.SPOTIFY_CLIENT_ID || ''
      ),
    },
    server: {
      host: '127.0.0.1',
      port: 5173,
      fs: {
        allow: [repoRoot],
      },
    },
    resolve: {
      alias: {
        '@app-config': appConfigAlias,
      },
    },
    plugins: [
      buzzerSoundsManifestPlugin(),
      react(),
      tailwindcss(),
      {
        name: 'app-config-html-transform',
        transformIndexHtml(html) {
          return html
            .replace(/%APP_DISPLAY_NAME%/g, appConfig.displayName)
            .replace(/%APP_SHORT_NAME%/g, appConfig.shortName)
            .replace(/%APP_DESCRIPTION%/g, appConfig.description);
        },
      },
      VitePWA({
        // Disable service worker to prevent redirect loops
        // Keep manifest for installability and fullscreen mode
        injectRegister: false,
        manifest: {
          name: appConfig.displayName,
          short_name: appConfig.shortName,
          description: appConfig.description,
          theme_color: '#22223b',
          background_color: '#f2e9e4',
          display: 'standalone',
          start_url: '/',
          icons: [
            {
              src: '/icon-192x192.png',
              sizes: '192x192',
              type: 'image/png',
            },
            {
              src: '/icon-512x512.png',
              sizes: '512x512',
              type: 'image/png',
            },
          ],
        },
        // No workbox configuration - service worker disabled
      }),
    ],
  };
});
